### ISSUE TITLE
not working on https://addons.mozilla.org/en-US/firefox/addon/text-contrast-for-dark-themes/reviews/add :)

### ISSUE THREAD

**Issue by matt32106** [DmitriK/darkContrast#11]
I wanted to leave a review for your addon and discovered that it does not work for the add reviews mozilla page :)

Works great on the sites i use usually, thanks !!

**Comment by matt32106** [comment]
I have read your explanation about why it does not work and am happy with the explanation, I close the issue.

**Comment by DmitriK** [comment]
If anyone else stumbles across this issue, the reason it cannot be fixed is because Firefox blocks all extension content scripts from running on addons.mozilla.org (see note at https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts), likely for security reasons (e.g. prevent malicious extensions from hijacking addon installation links/buttons).

**Comment by futpib** [comment]
Consider upvoting :+1: this issue mozilla/addons#657 if you care enough.
