### ISSUE TITLE
gmail site issue when setting a non-default theme

### ISSUE THREAD

**Issue by arigit** [DmitriK/darkContrast#13]
Found a problem with the gmail site.
When changing the default gmail theme to most of the other themes available (choose e.g. the first one, or any of the "solid" themes such as dark, soft grey, blue, etc), the left sidebar menu strings show a strange background color, that goes away / gets fixed when disabling darkContrast.

**Comment by DmitriK** [comment]
I see the issue with the names in the hangouts panel. The actual menu with the folders looks OK for me.

Using the dark theme as an example, the issue appears to be that the hangouts subsection is an iframe that has an explicit transparent background. because the parent document has a black background, gmail only sets the foreground color for some of the text. The extension only runs within the context of the iframe, so it doesn't know about the already specified black background, so attempts to fix the text by setting a white background, thus the funny looking text.

The extension does have some code that tries to handle the transparent iframe case, but it's clearly not working here. This may be due to the fact that the iframe is generated dynamically. I'll need to look into it.

**Comment by DmitriK** [comment]
The latest revision seems to have fixed the gmail weirdness on my end. Is this still an issue?

**Comment by arigit** [comment]
Thanks @DmitriK  for the follow up. Re-tested and compared with and without the addon, the issue seems fixed now. 
Closing!
