### ISSUE TITLE
Whatsapp

### ISSUE THREAD

**Issue by ghost** [DmitriK/darkContrast#16]
https://web.whatsapp.com/
The extension don't aplly on this page.

**Comment by DmitriK** [comment]
Unfortunately I don't have whatsapp, so I'm unable to see the page past the QR code. Ideally, I'd need the following three things to be able to figure out what's wrong, in increasing order of helpfulness:

- Screenshot
- Page source (Right click-> Save page as)
- Snapshot of the DOM after the extension has run (Ctrl+Shift+C, right click on <html> element, Copy->Outer HTML)

The nature of whatsapp means these things may contain sensitive data; I'd recommend navigating to some innocuous page first (maybe a settings page or something). You can also send it to me by email so that it's not public here on the issue tracker.

**Comment by DmitriK** [comment]
Closing due to age. There's been many changes since this bug, so hopefully it's been fixed.
