### ISSUE TITLE
Permanently enable force standard colors

### ISSUE THREAD

**Issue by thepycoder** [DmitriK/darkContrast#47]
Thank you for the nice extention!
One thing I'd like to see is a way to permanently enable the force standard colors toggle. It stops a lot of sites from looking bad and I don't want my desktop theme to interfere with any website anyway.

Maybe a wildcard in the exceptions box?
Thanks!

**Comment by DmitriK** [comment]
Since you don't want the desktop theme overriding anything, you may want to try the solution mentioned in #46, setting `widget.content.gtk-theme-override` to something like `Adwaita:light` in `about:config`. It would be much lighter than having all of this extension's heuristics loaded. This extension really works best for those who want to keep aspects of their dark theme in place where possible.

If the above solution doesn't work or doesn't fit your use case, let me know, I can think about how to best solve it.

**Comment by thepycoder** [comment]
Aha! I found it. Looked at the solution you metioned before, but didn't seem to find the `widget.content.gtk-theme-override` entry. After some searching on the arch linux forum, it appears `browser.display.use_system_colors` is the option I was searching for in `about:config`. Setting that to `false` fixed the ugly background colors for me and your extention is handling the rest of the text and readability issues perfectly, Thank You!
