### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by MathyV** [DmitriK/darkContrast#8]
Hi,

I'm using firefox 49.0 on Gentoo and am unable to install this add-on.

If I install it throught the add-on manager it just sits there forever saying it is downloading.
If I install it manually using the downloaded .xpi file, nothing happens, it doesn't show up.

Any tips to help debugging are welcome :-)

**Comment by DmitriK** [comment]
I'm not too sure what the issue might be.

Try installing the older version ([v0.7.1](https://addons.mozilla.org/en-US/firefox/addon/text-contrast-for-dark-themes/versions/?page=1#version-0.7.1)) and see if that works. I updated from using the older jetpack API to the new WebExtensions API in v1.0.0, so perhaps there's a hiccup there.

If Firefox is blocking the install, I'd like to think it would spit something out in the browser console, check if anything is reported there (I'm hoping it might report an API issue, or version mismatch, or something similar).

**Comment by MathyV** [comment]
Here is the output, seems something is wrong with the Manifest.

```
1478031387307   addons.webextension.<unknown>   WARN    Loading extension 'null': Reading manifest: Error processing author: An unexpected property was found in the WebExtension manifest.
1478031387307   addons.webextension.<unknown>   WARN    Loading extension 'null': Reading manifest: Error processing gecko: An unexpected property was found in the WebExtension manifest.
1478031387307   addons.webextension.<unknown>   WARN    Loading extension 'null': Reading manifest: Error processing homepage: An unexpected property was found in the WebExtension manifest.
1478031387307   addons.webextension.<unknown>   WARN    Loading extension 'null': Reading manifest: Error processing license: An unexpected property was found in the WebExtension manifest.
1478031387308   addons.webextension.<unknown>   WARN    Loading extension 'null': Reading manifest: Error processing title: An unexpected property was found in the WebExtension manifest.
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Tue Nov 01 2016 21:16:27 GMT+0100 (CET)
Full Message: TypeError:  is not iterable
Full Stack: AddonInstall.prototype.initLocalInstall/<@resource://gre/modules/addons/XPIProvider.jsm:5336:1
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:940:21
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:816:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:750:11
```

The previous version seems to install (and work!) fine.

Already thanks for an awesome add-on!

If you need me to test anything else, let me know.

**Comment by DmitriK** [comment]
Would be nice if the WebExt linter tool told me the manifest was full of deprecated keys. Anyway, I've removed the bad keys and uploaded a new version on AMO. I expect it'll be a few days before it goes through. I'm hoping that will fix the problem.

Could you try manually invoking an update through the addons settings page? I'm curious to see if an update of v0.7.1→v1.0.0 works, as opposed to a fresh install.

**Comment by MathyV** [comment]
Neither a manual or automatic update work.

I will report back once the new version is available if it installed.

**Comment by MathyV** [comment]
I'm sorry, but it still isn't working.

```
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Thu Nov 03 2016 22:08:11 GMT+0100 (CET)
Full Message: TypeError:  is not iterable
Full Stack: AddonInstall.prototype.onStopRequest/<@resource://gre/modules/addons/XPIProvider.jsm:5974:1
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:940:21
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:816:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:750:11
XPIProvider.jsm:5974
```

**Comment by DmitriK** [comment]
Hmm, none of those messages seem specific to my addon. I'm not sure what the problem might be. And since FF seems to be blocking the install, I don't think the addon is even running anything, so there's no way to use the JavaScript debugger.

It's good that 0.7.1 works for you, but it's a bummer if you end up stuck with it, as there are some significant performance improvements coming down the line in later versions.

I'm grasping here, but the following are the only things I can think of that could possibly be at play, in order of likeliness:

## Something Gentoo-specific

I noticed Gentoo adds some [specific configuration](https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/firefox/files/gentoo-default-prefs.js-1) settings to FF. I don't see how any of these would prevent install of the newest version. I tried running a temporary FF 49.0 instance to see if those settings interfere, and wasn't able to reproduce the issue.

However, the 'browser.display.use_system_colors' setting catches my eye. While I tried to make the addon do the right thing with that setting enabled, I don't run my browser with that setting on, so it's not very well tested. It's the only setting in the list that has relevance to this addon, so while I don't see how it could prevent install, you could try toggling it before updating/installing.

There might be something else about Gentoo that is messing up the Web Extensions API, like some USE flag that's needed or something. Can't imagine what it would be though.

## Another addon

I have no idea how another addon could possibly block installation, but maybe a script blocker  is preventing the script for my addon from running.

## Something wrong with the download:

Whether AMO is having issues, or something is corrupting the download en-route, maybe your .xpi is not correct once you get it. Now that I think about it, I can grab the signed .xpi files from AMO and put them in the github releases so that there's a second source of downloads.

**Comment by MathyV** [comment]
Was just checking the status on this and apparently v1.0.1 is now auto-updated on my system. Don't know if this is because of the add-on update or because my Firefox has been updated to v50 though.
